---
title: "Assignments"
output:
  blogdown::html_page:
    toc: true
    fig_caption: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

| Assignment | Due Date | Submit Via |
|-|-|-|
| [Grading Contract](#your-grading-contract) | February 5, 2021 | Upload to Github |
| [R Learner's Permit](#r-learners-permit) | February 19, 2021  | Upload to Github |
| [Class Reflections](#class-reflections) | Ongoing | Upload to Github |
| [Polished Lab Notebooks](#lab-notebook-extensions) | March, 2021</br> April, 2021 | Upload to Github |
| [Final Project Proposal](#project-proposal) | March 5, 2021  | Upload to Github |
| [Final Project Background](#project-background) | March 26, 2021  | Upload to Github |
| [Final Project Presentation](#project-presentation) | April 25, 2021  | Upload to Github |
| [Final Project](#final-project) | May 7, 2021  | Upload to Github |

# Your Grading Contract

**Due Date:** February 5, 2021 | **Submit Via:** Upload to Github

Our course syllabus outlines the approach to contract grading that we'll be using this semester. During the first two weeks of the class, you will develop your grading contact, which outlines the grade you are contracting for in the class as well as the agreed upon expectations for attaining that grade.

The grade you receive at the end of the class will be based on whether you did the work which you contracted for. Separately from this assessment, you will receive feedback on the qualities of your work.

Please use the following [contract template](/documents/UP494 S21 Learning Contract.docx) to construct your proposed learning contract for the semester. A few guidelines for constructing your contract:

- For most of you, your learning contract will include  the following baseline standard items in order to contract for a grade of "B": 
  - Class Interaction
      - *Attend Class Regularly:* Show up for course sessions before or on time, be absent from no more than three course sessions over the course of the semester. If you are unable to be present due to illness or other extenuating circumstances, please let me know before the course session in which you are absent, and I will consider excusing the absent.
      - *Participate Actively:* In addition to showing up to class sessions on time, you are expected to make thoughtful and informed contributions to our class community. This includes coming to class prepared and having completed readings, reflections and assignments. This also includes thoughtful engagement with course material, asking and responding to questions, and helping other students familiarize course concepts.
      - *Be Visible:* Due to necessary COVID-19 safety precautions, most of our synchronous course sessions will be offered via Zoom. Active participation in the discussion portions of our course ask that you engage with your camera on. If there are reasons you cannot meet this expectation, you may propose omitting or modifying this component of your contract.
      - *Submit Work On Time:* There will be three grade reconciliation periods in the semester. Each assignment will be due within a reconciliation period. Each assignment will also list a recommended due date. You are responsible for submitting your work by the end of the grade reconciliation period. Work due within a reconciliation period that is submitted within 48 hours of the conclusion of that period will be counted as late. Work due within a reconciliation period submitted more than 48 hours will be considered ignored.
  - Assignments  
      - *Class Reflections:* On a weekly basis, you will reflect **briefly** on a few questions that guide our work in that week.
      - *R Learner's Permit:* You will complete the R Learner's Permit notebook which tests your knowledge of basic R programming concepts.
      - *Lab Notebooks (3):* Throughout the course you will work with lab notebooks that are designed to help you learn new analytical concepts, approaches, and datasets. You will select three of these notebooks to polish and submit for review.
      - *Term Project Proposal:* You will develop a proposal for your term project, which asks you to perform an in-depth analysis around a theme of your choice. Your proposal will provide a broad overview rationale for your project, and will lay out details that will go into the project background and completed project.
      - *Term Project Background:* Your project background documentation will build upon your term project proposal. You will provide a detailed exploration of data and analysis strategies for your term project, and will also start to sketch out key outputs and findings.
      - *Completed Project:* You will produce a final project which will include a complete project rationale, background, and analysis. 
      - *Project Presentation:* Graduate students are required to prepare a 10-minute presentation on their project which they will give at the end of the semester. Undergraduates may elect to include a presentation as an extended component of their contract.
  - Contract Extensions and Deletions
    - You may propose contract extensions in order to contract for a higher grade. 
    - You may propose contract deletions in order to contract for a lower grade.

After you submit your proposed learning contract, we will schedule a 20-minute one-on-one meeting to discuss your goals and contract elements. After that meeting (and after any agreed upon revisions are made), we will sign your contract and you will be held to contracted standards. You will have one opportunity to revisit the terms of your contract around the middle of the semester.

## Submission Instructions

# Class Reflections
**Due Date:** Ongoing | **Submit Via:** Upload to Github

# R Learner's Permit
**Due Date:** February 19, 2021 | **Submit Via:** Upload to Github

# Lab Notebook Extensions
**Due Date:** 1 by X, 2 additional by Y | **Submit Via:** Upload to Github

Over the course of the semester, you will work on a series of lab notebooks which ask you to apply what you've learned in class to new data and analysis questions.


# Term Assignment

You will independently apply the skills and principles of data analysis we learn  to produce a policy-relevant analysis. Your term assignment will have several deliverables which are spread throughout the semester:

## Project Proposal
**Due Date:** March 5, 2021 | **Submit Via:** Upload to Github

You will develop a proposal that describes the analysis which you contract to complete by the end of the semester. Your proposal will include a statement regarding the motivation for your analysis, the information you plan to use, your analytical strategy, your anticipated outcomes, and information on the format of your final outputs.
## Project Background
**Due Date:** March 26, 2021| **Submit Via:** Upload to Github

You will prepare some general project background that includes a descriptive analysis.

## Final Project
**Due Date:** May 7, 2021 |**Submit Via:** Upload to Github

You will synthesize elements of your project proposal, project background, and additional analysis into a final project that includes analysis and interpretation.

## Project Presentation
**Due Date:** April 25, 2021 | **Submit Via:** Upload to Github

Graduate students are required to include a 10-minute presentation on their final project which will be given during one of our final course sessions as part of their grading contract. Undergraduate students are not required to complete a final project presentation, but may contract to do so for a higher grade (see more information on our approach to grades this semester below).

# Contract Extensions

Here are some ideas for contract extensions you may wish to propose (you can of course develop and propose other ideas as well):

- **Develop a Neighborhood Analysis Portfolio:** You could contract to create a portfolio of your analysis work over the course of the semester. This portfolio would include polished output suitable to share with a prospective employer or internship site.

- **Extend a Lab Notebook:** Over the course of the semester, you'll be working through several lab notebooks that walk you through techniques and approaches to different modes of neighborhood analysis. You could propose extending the analysis you are asked to do in these notebooks beyond what is asked of you in the lab. This might include a more expanded analysis of the data, or the application of the lab concepts to a different context or data of your choosing. Extending a lab notebook should involve producing some type of formalized output that is polished and ready for review..

- **Write an Op Ed:** Your final project asks you to perform a neighborhood-level analysis of your own design that is policy-relevant to a particular place. Based upon what your analysis reveals, you may have policy-relevant conclusions that it would be useful to share with a public audience. You can write an OpEd targeting a local newspaper that articulates a persuasive public argument and that draws substantively from your analysis. Good resources for this include [The OpEd Project](https://www.theopedproject.org), the [New York Times](https://www.nytimes.com/2017/08/25/opinion/tips-for-aspiring-op-ed-writers.html), [Goh and Bourne](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008187), and [Scientific American](https://blogs.scientificamerican.com/observations/if-you-want-to-explain-your-science-to-the-public-heres-some-advice/).

- **Develop a proposed extension to your final project:** It is likely that your final project will produce some insightful information drawing upon your analysis of existing data. It is also likely that through the process of conducting your analysis that you will reach the limits of what the data can tell you, and that you will have additional questions which you would like to answer. You can develop a proposed set of next steps based upon what you would do to continue to develop the analysis which you have conducted. This might include gaining insight from other sources of secondary data, applying other types of analytical techniques, or developing a plan for primary data collection to supplement your existing analysis.

These are a few suggested ways in which you can contract to extend your grade. You may have other ideas which you would like to propose. Please spend some time early in the class thinking about what your goals are this semester, and what work (in addition to our base expectations) might be part of this. Please be prepared to share these ideas when we meet one-on-one early in the semester to review your contract proposal. Of course we can also talk through some of these ideas in our class sessions during the first few weeks of class.
