---
title: Lab Notebooks
linktitle: Lab Notebooks
menu:
  assignments:
    parent: Assignments
    weight: 4
toc: true
type: docs
weight: 4
---

**Due Date:** 1 by March 19, 2021, 1 by April 21, 2021 | **Submit Via:** Upload to Github

Over the course of the semester, you will work on a series of lab notebooks which ask you to apply what you've learned in class to new data and analysis questions. These lab notebooks will guide you through learning new approaches to manipulating data. At the end of each notebook, there's information on how you might extend your analysis beyond the lab.

This course requirement asks you to choose two of these labs to produce a more polished analysis and data brief. You may select any of the labs to polish and to work with. You are expected to submit *at least* one of these polished notebooks in March and one in April.

Taking cues from the lab notebook and the prompts you will find at the end of the notebook, prepare a separate analytic notebook using RMarkdown that contains analysis and accompanying write-up. Your polished notebook should focus on interpreting the data itself, and posing and answering questions arising from the data (as opposed to focusing on intermediate data analysis steps). Using your notebook, you will weave together narrative description of the data with your analytic outputs, and should target creating a data brief of between 1,000-2,000 words plus analytic output.

## Helpful Resources
You may wish to reference the How To on [customizing code chunks](/howto/howto/07-customize_chunks/) to control how your output looks in your rendered notebook.

## Submission Instructions

Upload your polished lab notebooks to the appropriate folder in your class GitHub repository.