---
title: Contract Extension Ideas
linktitle: Extension Ideas
menu:
  assignments:
    parent: Your Contract
    weight: 7
toc: true
type: docs
weight: 7
---

Here are some ideas for contract extensions you may wish to propose (you can of course develop and propose other ideas as well):

- **Develop a Neighborhood Analysis Portfolio:** You could contract to create a portfolio of your analysis work over the course of the semester. This portfolio would include polished output suitable to share with a prospective employer or internship site.

- **Extend a Lab Notebook:** Over the course of the semester, you'll be working through several lab notebooks that walk you through techniques and approaches to different modes of neighborhood analysis. You could propose extending the analysis you are asked to do in these notebooks beyond what is asked of you in the lab. This might include a more expanded analysis of the data, or the application of the lab concepts to a different context or data of your choosing. Extending a lab notebook should involve producing some type of formalized output that is polished and ready for review.

- **Write an Op Ed:** Your final project asks you to perform a neighborhood-level analysis of your own design that is policy-relevant to a particular place. Based upon what your analysis reveals, you may have policy-relevant conclusions that it would be useful to share with a public audience. You can write an OpEd targeting a local newspaper that articulates a persuasive public argument and that draws substantively from your analysis. Good resources for this include [The OpEd Project](https://www.theopedproject.org), the [New York Times](https://www.nytimes.com/2017/08/25/opinion/tips-for-aspiring-op-ed-writers.html), [Goh and Bourne](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008187), and [Scientific American](https://blogs.scientificamerican.com/observations/if-you-want-to-explain-your-science-to-the-public-heres-some-advice/).

- **Develop a proposed extension to your final project:** It is likely that your final project will produce some insightful information drawing upon your analysis of existing data. It is also likely that through the process of conducting your analysis that you will reach the limits of what the data can tell you, and that you will have additional questions which you would like to answer. You can develop a proposed set of next steps based upon what you would do to continue to develop the analysis which you have conducted. This might include gaining insight from other sources of secondary data, applying other types of analytical techniques, or developing a plan for primary data collection to supplement your existing analysis.

These are a few suggested ways in which you can contract to extend your grade. You may have other ideas which you would like to propose. Please spend some time early in the class thinking about what your goals are this semester, and what work (in addition to our base expectations) might be part of this. Please be prepared to share these ideas when we meet one-on-one early in the semester to review your contract proposal. Of course we can also talk through some of these ideas in our class sessions during the first few weeks of class. As part of your contract proposal you will need to write a description of each extended contract component. Please be prepared to share this when we meet.